# Generated by Django 4.2.13 on 2024-05-18 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rate', '0001_initial_model_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='rater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rater_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('post', 'rater')},
        ),
    ]
